# Docker Compose version
version: '3.8'  


# Defines the containers that will be used for the application
services:

  # Node.js service
  node:
    build: ./node            # Dockerfile located in the './node' directory
    ports:
      - 3000:3000            # Mapping port 3000 of the host to port 3000 of the container
    restart: always
    image: shahar1041/super-app:node


  # MySQL database service
  db:
    image: mysql:8.0.28      
    environment:
    # Using Environment variables setting up MySQL database name and password
      MYSQL_DATABASE: super-app   
      MYSQL_ROOT_PASSWORD: password  
    ports:
      - 3306:3306            # Mapping port 3306 of the host to port 3306 of the container
    restart: always          

  # PHP service
  php:
    build: ./php             # Dockerfile located in the './php' directory
    ports:
      - 80:80                # Mapping port 80 of the host to port 80 of the container
    restart: always
    image: shahar1041/super-app:php


